### ISSUE TITLE
New dependency name: uglify-es => terser

### ISSUE THREAD

**Issue by fabiosantoscode** [duan602728596/gulp-terser#1]
There has been development on a new fork of uglify-es, which is now called terser and has its own package!

    "terser": "^3.7.3"

Please upgrade to our new version.

**Comment by duan602728596** [comment]
@fabiosantoscode 
If the name of uglify-es is changed to terser, isn't the plugin also called gulp-terser?

**Comment by fabiosantoscode** [comment]
The name of the plugin is up to you :)

**Comment by rodrigograca31** [comment]
this issue can be closed.
