### ISSUE TITLE
How are changes logged?

### ISSUE THREAD

**Issue by anselmbradford** [duan602728596/gulp-terser#11]
This repo doesn't appear to have a changelog or releases, other than those listed on https://www.npmjs.com/package/gulp-terser. Are changes per release listed anywhere? I had to look into [the commit](https://github.com/duan602728596/gulp-terser/commit/28139588949b83cfa58985296dae43e4ffc9aa76) for the latest release.

**Comment by duan602728596** [comment]
Sorry, this is caused by my laziness. From this version, I will write the upgrade log.
