### ISSUE TITLE
Doesnt output to the right folder

### ISSUE THREAD

**Issue by rodrigograca31** [duan602728596/gulp-terser#13]
The following code should take the file from `js/` folder and write it into `build/js/` but it writes it to `./build` root.

```javascript
const gulp = require('gulp');
const terser = require('gulp-terser');

gulp.task('default', function (callback) {
    return gulp.src('./js/index.js')
    .pipe(terser())
    .pipe(gulp.dest('./build'));
});
```

I know I could change to where it writes, the bigger problem arises when you have multiple folders with JS code and use: `**/*.js` and then doesnt write to the corresponding folders.....
Here is a tiny demo: [gulp-terser.zip](https://github.com/duan602728596/gulp-terser/files/3768855/gulp-terser.zip)

**Comment by rodrigograca31** [comment]
:thinking: :thinking: :thinking: :thinking: :thinking: 

Actually I was testing with `cleanCSS` which works as intended and decided to use the same exact parameters and seem it actually works:
```javascript
const gulp = require('gulp');
const cleanCSS = require('gulp-clean-css');

gulp.task('default', function () {
    return gulp.src('**/*.css')
    .pipe(cleanCSS())
    .pipe(gulp.dest('./build'));
});
```

so then I decied to run:
```javascript
gulp.task('default', function (callback) {
    return gulp.src('**/*.js')
    .pipe(terser())
    .pipe(gulp.dest('./build'));
});
```

and seems to work as intended....

**Comment by duan602728596** [comment]
`./js/index.js`, it specifies the specific location of the file, so it won't contain the folder.
`**/*.js`, it matches all the files that match the result in the path, so its path is the folder containing it.
You can refer to [glob](https://github.com/isaacs/node-glob), because many tools get the path to the file using the [glob](https://github.com/isaacs/node-glob).

**Comment by rodrigograca31** [comment]
:muscle: Exactly. My bad
