### ISSUE TITLE
TypeError in plugin "terser"

### ISSUE THREAD

**Issue by radogado** [duan602728596/gulp-terser#14]
Hi, any idea why this error is happening?

`[17:24:11] TypeError in plugin "terser"
Message:
    The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
Details:
    code: ERR_INVALID_ARG_TYPE
    domainEmitter: [object Object]
    domainThrown: false
`

when using the following code, which worked 2 weeks ago:

`gulp.task('build:scripts', function () {
    return gulp.src(config.app_files.js)
        .pipe(sourcemaps.init())
        .pipe(rollup({ }, { format: 'cjs', strict: false }))
        .pipe(concat('script.js'))
        .pipe(terser())
        .pipe(rename(function (path) {
            path.extname = ".min.js"
        }))
        .pipe(sourcemaps.write('.', {
            mapFile: function (mapFilePath) {                
                return mapFilePath.replace('.js.map', '.map');
            }
        }))
        .pipe(gulp.dest(config.build_dir));
});
`

Thanks!

**Comment by duan602728596** [comment]
This error is caused by the v5 version of terser, the `terser.minify` function was adjusted from synchronous to asynchronous. Now this problem has been fixed.

**Comment by radogado** [comment]
Thanks so much for your quick reply and fix. Have a nice day.

**Comment by duan602728596** [comment]
> Thanks so much for your quick reply and fix. Have a nice day.

😀
