### ISSUE TITLE
minify: SyntaxError: Unexpected token function

### ISSUE THREAD

**Issue by johnathanmelo** [duan602728596/gulp-terser#17]
I have faced a issue when running v1.3.2 at **node_modules/terser/dist/bundle.min.js:23478**

Location of the error:
async function minify(files, options)

Error message:
SyntaxError: Unexpected token function

**Comment by duan602728596** [comment]
What is the version of your node?

**Comment by ignotummisterrii** [comment]
i have the same issue

**versions:**
- node 6.11.0
- gulp-terser@1.4.0
- terser@5.3.1

**Comment by duan602728596** [comment]
> i have the same issue
> 
> **versions:**
> 
> * node 6.11.0
> * gulp-terser@1.4.0
> * terser@5.3.1

Your node version is too low. It is recommended that you upgrade the node version; or use npm to install terser4; or configure the following in package.json,

```json
"resolutions": {
  "terser": "^4.8.0"
}
```
then install the dependencies with yarn.

**Comment by ignotummisterrii** [comment]
> > i have the same issue
> > **versions:**
> > 
> > * node 6.11.0
> > * gulp-terser@1.4.0
> > * terser@5.3.1
> 
> Your node version is too low. It is recommended that you upgrade the node version; or use npm to install terser4; or configure the following in package.json,
> 
> ```json
> "resolutions": {
>   "terser": "^4.8.0"
> }
> ```
> 
> then install the dependencies with yarn.

I can't upgrade my node version yet, but with terser **4.8.0** it's work, thank you :D !
