### ISSUE TITLE
TypeError in plugin "terser"

### ISSUE THREAD

**Issue by vishal-nummo** [duan602728596/gulp-terser#19]
Suddenly running into the following error with gulp 

[11:15:25] TypeError in plugin "terser"
[INFO] Message:
[INFO]     The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type undefined
[INFO] Details:
[INFO]     code: `ERR_INVALID_ARG_TYPE`
[INFO]     domainEmitter: [object Object]
[INFO]     domainThrown: false
[INFO] 
[INFO] [11:15:25] 'build' errored after 1.35 s
[INFO] npm ERR! code `ELIFECYCLE`

Running version "gulp-terser": "~1.2.0"
Node version v12.14.0

**Comment by duan602728596** [comment]
You can try to upgrade to the latest version

**Comment by vishal-nummo** [comment]
Issue resolved after upgrading to latest version.
