### ISSUE TITLE
libs.js:4 Uncaught TypeError: Cannot set property window of #<Window> which has only a getter

### ISSUE THREAD

**Issue by DarceyLloyd** [duan602728596/gulp-terser#21]
Using some libs after gulp-terser is run js errors are caused:

libs.js:4 Uncaught TypeError: Cannot set property window of #<Window> which has only a getter.
![image](https://user-images.githubusercontent.com/932191/97111464-d5295400-16d6-11eb-988c-f7ba6989af71.png)

So I created a test folder and setup the following:

1. CMD: npm init -y
2. CMD: npm i -S gsap gulp gulp-contact gulp-terser gulp-rename
3. Create gulpfile.js

```
const gulp = require("gulp");
const concat = require('gulp-concat');
const terser = require('gulp-terser');

let jsFiles = [
   "./node_modules/gsap/dist/gsap.js",
];
 
let buildLibsProd = function (done) {
    gulp.src(jsFiles)
        .pipe(concat('libs.min.js'))
        .pipe(terser())
        .on("error", function (e) {
            console.log(e.toString());
            this.emit("end");
        })
        .pipe(gulp.dest('./'));
    done();
};
// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
gulp.task("build", gulp.parallel(
    buildLibsProd
));
// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
```

4. Run gulp build
5. Create index.html
6. Add script tag link in head to libs.min.js (will give you console log error).
7. Comment out script tag from point 6 and add another script tag link in head to ./node_modules/gsap/dist/gsap.min.js (no console errors)

 Any ideas?

**Comment by duan602728596** [comment]
I can successfully compile and get the gsap object. What is the problem with you?
![Uploading 1.png…]()

**Comment by DarceyLloyd** [comment]
I just started to create a public git repo, built from scratch and found it worked... Done a little visual compare on files and found auto complete inserted 

`type="module" `

Into the script tag...

Well ****... Can't believe I missed that... It's always the smallest of things that get you...

@duan602728596 Thanks for taking a look though :)
