### ISSUE TITLE
warning gulp-terser@2.0.0: The engine "terser" appears to be invalid.

### ISSUE THREAD

**Issue by BobbyWibowo** [duan602728596/gulp-terser#23]
I keep on getting the following error when doing any `yarn` add/remove operations:
```
warning gulp-terser@2.0.0: The engine "terser" appears to be invalid.
```
Is there something that I'm missing?

**Comment by duan602728596** [comment]
No, just use it normally.

**Comment by tjkohli** [comment]
Getting this too. It's flagging in our CI/CD pipelines. Is there a way to resolve the warning?

**Comment by BobbyWibowo** [comment]
You can only either manually patch it with this commit https://github.com/duan602728596/gulp-terser/commit/debee88a927bd0264fa416985d8042ba91a1e437, or wait for a release that includes it.

**Comment by duan602728596** [comment]
A new version has been released.
