### ISSUE TITLE
SyntaxError: Unexpected token: keyword (function)

### ISSUE THREAD

**Issue by phonowell** [duan602728596/gulp-terser#24]
```
gulp.src(source, { base, sourcemaps })
        .pipe(tsProject())
        .pipe(gulpIf(!!minify, terser({ safari10: true })))
        .pipe(gulp.dest(target, this.returnSourcemaps(sourcemaps)))
        .on('end', () => resolve(true))
```
With `gulp@4.0.7` & `gull-terser@2.0.0`, got this error message.
Need help.

**Comment by duan602728596** [comment]
You can try to configure the `ecma` of `terser`.

**Comment by phonowell** [comment]
Doesn't seem to work, still throwing errors.
Whether `ecma` is `5`, `2015` or `2016`.

**Comment by duan602728596** [comment]
Can you post the code? It seems that the version of ecma is still too low.
