### ISSUE TITLE
Support gulp-sourcemaps

### ISSUE THREAD

**Issue by c-bandy** [duan602728596/gulp-terser#3]
Unlike gulp-uglify, gulp-terser does not have support for [gulp-sourcemaps](https://github.com/gulp-sourcemaps/gulp-sourcemaps), but instead garbles outputted sourcemaps. 

Can this be added?

**Comment by duan602728596** [comment]
@c-bandy The version has been updated. This feature is already available :) .

**Comment by c-bandy** [comment]
It seems to not work. None of my files get added to sources in the map, and all `names` are missing.

**Comment by duan602728596** [comment]
@c-bandy It is ok now.

**Comment by c-bandy** [comment]
Thanks for the quick fix! 

You could probably be asked to be added to [the list of supported plugins](https://github.com/gulp-sourcemaps/gulp-sourcemaps/wiki/Plugins-with-gulp-sourcemaps-support).

**Comment by elliot-nelson** [comment]
`gulp-terser` is now on the list! :+1:

(Tested on my own project and the source maps are working great in Chrome.)

**Comment by binarykitchen** [comment]
can this be documented? 

do I still have to call `sourcemaps.init()` before gulp-tersing and `sourcemaps.write('/')` afterwards?

**Comment by duan602728596** [comment]
@binarykitchen Need to be called `sourcemaps.init()`.

**Comment by binarykitchen** [comment]
so it is still needed. can you add this to readme?

**Comment by duan602728596** [comment]
@binarykitchen It is ok.
