### ISSUE TITLE
getting error "The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type undefined".

### ISSUE THREAD

**Issue by varungpt** [duan602728596/gulp-terser#5]
error:
```
Plumber found unhandled error:
 TypeError [ERR_INVALID_ARG_TYPE] in plugin "terser"
Message:
    The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type undefined
```
I am using this code:

```
const gulp = require('gulp');
const terser = require('gulp-terser');

gulp.task('default', function() {
  return gulp.src(['js/*.js'])
    .pipe(plumber())
    .pipe(terser())
    .pipe(gulp.dest('../assets/js'));
});
```
I also tried to pass {ecma:8} in terser as `.pipe(terser({ecma:8}))` but it doesn't resolve the problem.

**Comment by duan602728596** [comment]
I tested it and found no problem. Do you try to use the terser compression instead of gulp? @varungpt

**Comment by varungpt** [comment]
Hey thanks for the reply, the issue was in my code, I do not exactly know what was the problem yesterday but the issue has been resolved now. I am really sorry for wasting your time.

**Comment by SinuheM** [comment]
Hello, I get the same error

```
TypeError [ERR_INVALID_ARG_TYPE] in plugin "terser"
Message:
The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type undefined
```
It works when I dont set any Terser configuration, or use the example in the readme file but with the drop_console option throw the error message
```
const { src, dest } = require('gulp');
const  useref = require('gulp-useref'),
	  terser = require('gulp-terser'),
	  gulpif = require('gulp-if');

function jsDeploy(){
	return src('dist/*.html')
        .pipe(useref())
        .pipe(gulpif('*.js', terser({drop_console: true})))
	.pipe(dest('dist'));
}
```

**Comment by duan602728596** [comment]
Can you give me a demo file? I have tested and found that no matter whether the version of gulp is 3.9.1 or 4.0.0, this error does not occur.

At 2019-01-07 16:17:57, "Adrián Prialé Cordova" <notifications@github.com> wrote:


Hello, I get the same error

TypeError [ERR_INVALID_ARG_TYPE] in plugin "terser"
Message:
The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type undefined


It works when I dont set any Terser configuration, or use the example in the readme file but with the drop_console option throw the error message

const { src, dest } = require('gulp');
const  useref = require('gulp-useref'),
	  terser = require('gulp-terser'),
	  gulpif = require('gulp-if');

function jsDeploy(){
	return src('dist/*.html')
        .pipe(useref())
        .pipe(gulpif('*.js', terser({drop_console: true})))
	.pipe(dest('dist'));
}

**Comment by SinuheM** [comment]
This is my package.json and gulpfile.js 
[error_drop.zip](https://github.com/duan602728596/gulp-terser/files/2733805/error_drop.zip)
